### ISSUE TITLE
loading saved model

### ISSUE THREAD

**Issue by kroskal** [deeplizard/Keras_Jupyter_Notebooks#2]
Hi, 
I'm following your tutorial on fine tuning the VGG16 model in Keras. Loving it!
But I have an issue when I save the model after training and then try to load the model again. 
I get the following error:
![load_model_error](https://user-images.githubusercontent.com/22024776/35382353-40da592c-01bf-11e8-882a-cb2dc9801166.PNG)

I havent done anython to the code other than "save" and "load_model". 
Any clues why this is happeing?

**Comment by deeplizard2** [comment]
Hey kroskal - Glad you're liking the videos! 

I just went into the notebook I used in the videos and saved the trained fine-tuned VGG16 model and then loaded the model, just as you did in your code. I did not have an issue. Did you run the previous code of building and fine-tuning the model just as I did in the videos? Also, what's your Python and Keras versions?

**Comment by kroskal** [comment]
Hi, 
I run Keras 2.1.2 and Python 3.6.3.
And I've run all previous code but I get some dimension missmatch. I found a workaround that worked for me using the functional api. What I've read from other sources, is that model.layers.pop() does not remove the laste layer properly. 

> model.layers.pop is just a list pop, while model.output isn't taken care and replaced with the real output you want.
